name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch code
        uses: actions/checkout@v6.0.2
      - name: Set up mise
        uses: jdx/mise-action@v3.6.1
      - name: Check bin-paths
        shell: pwsh
        run: |
          mise bin-paths maven
